Add six to requirements.txt
docker/docker-py pull request #2844
Opened 2021-05-20 19:35 UTC by NitzanDevOpser

Made sure all imports contained in the package would have a corresponding requirement:
- grep'ed for 'import' or from, under docker/ dir 
- Filtered out local imports (starting with dot), and 'docker.' imports
- Print only imported module (awk)
- Sort, unique
$ grep -rh -e "^import\b" -e "^from\b"  docker/ | grep -v " \." | grep -v docker |  awk '{print $2}' |sort -u

Imported all listed output in a clean python:3.8-slim docker and caught ImportError exceptions - printing the missing packages
Made sure every* error'ed package is included in the requirements.txt, installed updated requirement.txt and ran import script again - No errors.

* Only exception is the windows-related modules which are imported only for windows.

** Unclear why 'six' was removed on March 2021 (commit: c8fba210)

2021-05-20 19:55 UTC, thaJeztah commented
@NitzanDevOpser thanks! looks like I don't have edit permissions in this repository, but could you add:

fixes https://github.com/docker/docker-py/issues/2807
fixes https://github.com/docker/docker-py/issues/2842

to your PR description?


@ulyssessouza @ndeloof ptal

2021-05-20 20:13 UTC, NitzanDevOpser commented
Done.

Both on commit msg and this PR's 1st comment

2021-05-20 20:26 UTC, thaJeztah commented
Thanks!

2021-06-02 11:14 UTC, MartinWallgren commented
It needs to be re-added to setup.py too

2021-06-02 12:34 UTC, NitzanDevOpser commented
@MartinWallgren, Right.

Done

2021-06-09 15:51 UTC, e0ne approved these changes

2021-06-17 00:15 UTC, JonZeolla approved these changes

2021-06-17 00:17 UTC, JonZeolla commented
@aiordache or @ulyssessouza would one of you mind taking a look a this?  It seems like a rather simple bug introduced in 5.0.0 that likely warrants a patch release.

2021-06-17 15:48 UTC, JonZeolla requested changes
I would have expected CI to fail, but it [succeeded](https://github.com/docker/docker-py/runs/2280319072#step:4:62) because CI installs `six` due to a bunch of transitive dependencies in `test-requirements.txt` and `requirements.txt`[1].

I suggest this PR gets some improved tests to ensure this kind of issue doesn't reoccur.  It's also requested by the [contributor docs](https://github.com/docker/docker-py/blob/master/CONTRIBUTING.md#7-add-tests).

One way to fix this is to pick up [this work in progress](https://github.com/docker/docker-py/commit/71411f5596dd0b3ef523af3b0af4c81e2827cc04).  I may give that a try if that's the preferred direction.

There does seem to be a preference for using `requirements.txt` and `test-requirements.txt` for testing (`make test` does this, as does CI and `tox.ini`), but I would think we would at least want to also test with `setup.py`.  Any thoughts on that?

Alternatively, since `setup.py` indicates `websocket-client >= 0.32.0` but `requirements.txt` requires `websocket-client==0.56.0` perhaps `websocket-client >= 0.32.0, < 1` in `setup.py` is another way to solve this problem.  Not my favourite approach, but keeps `install_requires` pretty minimal.  This would also require testing the `setup.py` installation approach.

Open to feedback on the preferred approach, especially from the maintainers.  Sorry for all the questions; I'd be happy to contribute once there's some more clear preferences/direction.

1: `pytest-cov==2.6.1` and `pytest-timeout==1.3.3` in `test-requirements.txt`, as well as `websocket-client==0.56.0`, `paramiko==2.4.2`, `packaging==16.8`, and `pyOpenSSL==18.0.0` in `requirements.txt`

2021-07-08 23:40 UTC, JonZeolla commented
Duplicate of https://github.com/docker/docker-py/pull/2863

2021-07-09 11:27 UTC, thaJeztah commented
> Duplicate of #2863

I see that one was merged; is this one closable?

2021-08-13 12:51 UTC, JonZeolla commented
@thaJeztah yes I believe this should be closed.

2021-08-13 13:10 UTC, thaJeztah commented
Thanks! Let me close this one. Thanks for contributing, @NitzanDevOpser !!

2021-08-13 13:11 UTC, closed without merging