Add `one-shot` to container API `stats`
docker/docker-py pull request #3089
Opened 2023-01-25 15:25 UTC by aroxby-wayscript

Add the `one-shot` parameter to container stats to enable pulling just a single stats update.  New in docker engine [20.10.0](https://docs.docker.com/engine/release-notes/#20100).

See the moby PR: https://github.com/moby/moby/pull/40478

2023-01-26 21:58 UTC, milas requested changes
Thanks for the PR!

Two adjustments:

1. Since this was added in v1.41, we should check the API version if the param is set, which will realistically mean changing the default to `one_shot=None`. See [an example in another API call](https://github.com/docker/docker-py/blob/34e6829dd40e99e9ba47ea02fcfabda09e08d36e/docker/api/container.py#L441-L446)
2. `one_shot=True` is only valid if `stream=False`, so we should check that as an invariant here and raise an exception, as otherwise it'll be rather hard to debug because of the stream helper in some cases (normally I'd say rely on server-side validation, but in this case there's no sensible meaning to the combo, so it seems safe enough to add a redundant check for)

2023-01-27 21:43 UTC, aroxby-wayscript commented
@milas, thanks for that very helpful and clear feedback.  I believe this is what you'd want to see.

2023-02-03 20:01 UTC, milas requested changes
One small tweak but LGTM otherwise. Thanks for making the changes!

2023-02-03 20:01 UTC, milas commented on docker/api/container.py
> +            if one_shot is not None:
```suggestion
            if one_shot:
```
It'd also be valid to explicitly pass `one_shot=False`

2023-02-06 20:14 UTC, aroxby-wayscript commented
@milas thanks again for all your helpful feedback.  How are we looking on this?

2023-02-13 15:04 UTC, aroxby-wayscript commented
@milas just sending another ping on this.  Look good?

2023-02-14 15:54 UTC, milas approved these changes

2023-02-16 15:27 UTC, merged